sudo: required

language: node_js
node_js:
  - "node"
  - "4"

cache:
  directories:
    - ./node_modules

#services:
#  - docker

#before_install:
#  - docker build -t klaakso/berrypod-server .

#after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push klaakso/berrypod-server;
#    fi

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python
