language: node_js
node_js:
  - "node"
  - "4"

cache:
  directories:
    - ./node_modules

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    curl -H "Content-Type&#58 application/json" --data '{"build" &#58 true}' -X POST https&#58//registry.hub.docker.com/u/klaakso/berrypod-server/trigger/$DOCKER_TRIGGER_TOKEN/;
    fi